[versions]
# libraries
archunit = "1.5.1"
junit = "4.13.2"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.19.0"
kotlin = "2.4.20"
kover = "0.9.11"
ktfmt = "0.27.0"

[libraries]
archunit = { group = "com.tngtech.archunit", name = "archunit", version.ref = "archunit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
